"""correct_star_date_add_indexes

Revision ID: a69600a3abca
Revises: c02df5295395
Create Date: 2025-10-20 14:50:36.436252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a69600a3abca'
down_revision: Union[str, Sequence[str], None] = 'c02df5295395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('car_vin_key'), 'car', type_='unique')
    op.create_index(op.f('ix_car_vin'), 'car', ['vin'], unique=True)
    op.create_index('claim_index', 'claim', ['car_id', 'claim_date'], unique=False)
    op.add_column('insurance_policy', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.create_index('insurance_policy_index', 'insurance_policy', ['car_id', 'start_date', 'end_date'], unique=False)
    op.drop_column('insurance_policy', 'star_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_policy', sa.Column('star_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index('insurance_policy_index', table_name='insurance_policy')
    op.drop_column('insurance_policy', 'start_date')
    op.drop_index('claim_index', table_name='claim')
    op.drop_index(op.f('ix_car_vin'), table_name='car')
    op.create_unique_constraint(op.f('car_vin_key'), 'car', ['vin'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
